In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 0.22386841, -0.14640757,  0.23343169, ..., -0.46448499,
        -0.07479713,  0.4475215 ],
       [-0.59343182, -1.08837064, -0.5778586 , ..., -0.75210969,
        -0.24716027, -0.05232627],
       [ 0.31687154,  0.68179183,  0.27768389, ...,  0.13260345,
         0.45542473,  0.74950151],
       ...,
       [ 0.81570652, -0.07587411,  0.87099114, ...,  2.17246201,
         0.34708219,  0.36194233],
       [ 0.2379598 , -0.8881466 ,  0.21745173, ...,  0.36958019,
         0.09264136, -0.01907576],
       [-0.11714306, -0.34208106, -0.16483809, ..., -0.83404478,
        -0.8988571 , -0.75385744]], shape=(455, 30))

In [9]:
y_train

498    M
455    B
382    B
158    B
300    M
      ..
296    B
142    B
253    M
62     M
81     B
Name: diagnosis, Length: 455, dtype: str

### Label Encoding

In [9]:
encoder = LabelEncoder()  # as diagonisis are in the alphabet we encode them in number her 0 and 1 
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0])

Numpy arrays to PyTorch tensors

In [11]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32)) # this is neccessary as builtin function will use the float instead of the double type tensors
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [13]:
y_train_tensor.shape

torch.Size([455])

In [14]:
from torch.utils.data import Dataset,DataLoader

In [15]:
class CustomDataset(Dataset):

    def __init__(self,features,labels):

        self.features=features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self,index):

        return self.features[index],self.labels[index]

In [16]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [17]:
train_dataset[10]

(tensor([ 0.0689,  1.7239,  0.0044, -0.0341, -1.9110, -1.0069, -0.6884, -0.8245,
         -0.4023, -1.1837, -0.6309, -0.5435, -0.5665, -0.4363, -0.5626, -0.4950,
         -0.4104, -0.8771, -0.7734, -0.7070, -0.1919,  0.9979, -0.2140, -0.2662,
         -1.3319, -0.7026, -0.6042, -0.9047, -0.9071, -1.0537]),
 tensor(0.))

In [18]:
train_loader= DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader= DataLoader(test_dataset,batch_size=32,shuffle=True)

# Defining the model

In [19]:
class mySimpleNN(nn.Module):

    def __init__(self,num_features):

        super().__init__()
        self.linear  = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):

        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [20]:
learning_rate = 0.1 
epochs = 25

In [24]:
# create model 
model = mySimpleNN(X_train_tensor.shape[1])


# Define optimizer 
optimizer= torch.optim.SGD(model.parameters() , lr=learning_rate) # using the builtin SGD

# Define loss function 
loss_function = nn.BCELoss() # binary cross entropy loss built in in nn module

# Training pipeline

In [ ]:


#define loop

for epoch in range(epochs):
    #forward pass 
    for batch_features,batch_labels in train_dataset:
        # print(y_pred)
            

        # loss calculate

        # loss = loss_function(y_pred,y_train_tensor) this gives error due to shape mismatch 
        loss = loss_function(y_pred,y_train_tensor.view(-1,1))

        # clear gradients 
        optimizer.zero_grad()  


        # backward pass
        loss.backward()

   
        # parameter update using the optimizer 
        optimizer.step()

        # optimizer.zero_grad()   It is recommended to clear them before the backward pass 

        # print los in each epoch : 
        print(f"Epoch : {epoch} , Loss : {loss.item()}")



    # model.weights

Epoch : 0 , Loss : 0.7116937041282654
Epoch : 1 , Loss : 0.5435733795166016
Epoch : 2 , Loss : 0.4537237584590912
Epoch : 3 , Loss : 0.3978376090526581
Epoch : 4 , Loss : 0.3590677082538605
Epoch : 5 , Loss : 0.33021312952041626
Epoch : 6 , Loss : 0.30768027901649475
Epoch : 7 , Loss : 0.28946012258529663
Epoch : 8 , Loss : 0.27433347702026367
Epoch : 9 , Loss : 0.26151326298713684
Epoch : 10 , Loss : 0.2504667043685913
Epoch : 11 , Loss : 0.24081893265247345
Epoch : 12 , Loss : 0.23229770362377167
Epoch : 13 , Loss : 0.22470015287399292
Epoch : 14 , Loss : 0.2178715616464615
Epoch : 15 , Loss : 0.21169161796569824
Epoch : 16 , Loss : 0.20606522262096405
Epoch : 17 , Loss : 0.20091590285301208
Epoch : 18 , Loss : 0.1961815506219864
Epoch : 19 , Loss : 0.19181090593338013
Epoch : 20 , Loss : 0.18776129186153412
Epoch : 21 , Loss : 0.1839967966079712
Epoch : 22 , Loss : 0.18048690259456635
Epoch : 23 , Loss : 0.17720550298690796
Epoch : 24 , Loss : 0.17413005232810974

# Evaluation

In [30]:
# model evaluation 

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred> 0.8).float()  # if the y_pred is above 0.5 set to 1 
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy : {accuracy.item()}')

print(type(y_pred))
# if y_pred>0.5:
#     y_pred=1
# else:
#     y_pred=0

Accuracy : 0.5706371068954468
<class 'torch.Tensor'>