In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[-0.72184682, -1.95646459, -0.73827127, ..., -1.01856329,
         0.81748415, -0.51051637],
       [ 0.95527803,  0.01829924,  0.93865098, ...,  1.20616417,
         0.05301906, -0.27248458],
       [-0.99298201,  0.22496057, -0.88338564, ...,  0.48758099,
        -0.49468212,  1.99953716],
       ...,
       [-1.2118468 ,  0.16066594, -1.20928496, ..., -1.37239728,
        -1.59173916,  0.3437594 ],
       [ 0.23411434, -0.03221797,  0.2061882 , ...,  0.52396495,
         0.10927839,  0.06010026],
       [-0.46189247, -0.4432444 , -0.46587781, ..., -0.13701029,
         0.2300705 , -0.38572834]], shape=(455, 30))

In [11]:
y_train

313    B
201    M
376    B
213    M
172    M
      ..
329    M
104    B
97     B
291    B
497    B
Name: diagnosis, Length: 455, dtype: str

### Label Encoding

In [12]:
encoder = LabelEncoder()  # as diagonisis are in the alphabet we encode them in number her 0 and 1 
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0])

Numpy arrays to PyTorch tensors

In [14]:
y_test

array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1])

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_train_tensor.shape

torch.Size([455, 30])

In [17]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [18]:
class mySimpleNN():
    def __init__(self,X):

        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64 , requires_grad=True) # this gives us 30 * 1 matrix of weight
        self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias # z = wx + b
        y_pred = torch.sigmoid(z)   # activation functions
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()  # this is formula for binary cross entropy loss function 
        return loss

### Important Parameters

In [19]:
learning_rate = 0.1 
epochs = 50

### Training Pipeline

In [20]:
# create model 
model = mySimpleNN(X_train_tensor)
#defin loop

for epoch in range(epochs):
    #forward pass 
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)
        

    # loss calculate

    loss = model.loss_function(y_pred,y_train_tensor)
    # print(f"Epoch : {epoch} Loss : {loss.item()}")

    # backward pass
    loss.backward()

    # parameters update  # wnew = wold - lr.( dL / dW)  and new bias  = bold - lr (dL / db) here lr is learning rate and it is called n eta
    with torch.no_grad():    
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad


    # zero gradients as gradient accumulates so clering them

    model.weights.grad.zero_()
    model.bias.grad.zero_()
    

    # print los in each epoch : 
    print(f"Epoch : {epoch} , Loss : {loss.item()}")



# model.weights

Epoch : 0 , Loss : 3.160056921767943
Epoch : 1 , Loss : 3.0241128861576305
Epoch : 2 , Loss : 2.8866334367142135
Epoch : 3 , Loss : 2.745705619839716
Epoch : 4 , Loss : 2.601198064008643
Epoch : 5 , Loss : 2.4456682763670146
Epoch : 6 , Loss : 2.2897565626684213
Epoch : 7 , Loss : 2.1355394578591804
Epoch : 8 , Loss : 1.9812697139175899
Epoch : 9 , Loss : 1.8301891950485447
Epoch : 10 , Loss : 1.6842224109034039
Epoch : 11 , Loss : 1.547158009751177
Epoch : 12 , Loss : 1.4206254449628983
Epoch : 13 , Loss : 1.3067303286885583
Epoch : 14 , Loss : 1.205794602558134
Epoch : 15 , Loss : 1.1207355737074411
Epoch : 16 , Loss : 1.051277831575881
Epoch : 17 , Loss : 0.9962700275952077
Epoch : 18 , Loss : 0.9537939325791829
Epoch : 19 , Loss : 0.9215110055007765
Epoch : 20 , Loss : 0.8970408953499936
Epoch : 21 , Loss : 0.8782354696014705
Epoch : 22 , Loss : 0.8633453388281734
Epoch : 23 , Loss : 0.8510825565652717
Epoch : 24 , Loss : 0.840577658494658
Epoch : 25 , Loss : 0.8312772015167247
Epoch : 26 , Loss : 0.8228392924591256
Epoch : 27 , Loss : 0.8150541688696705
Epoch : 28 , Loss : 0.8077916992663404
Epoch : 29 , Loss : 0.800968991526054
Epoch : 30 , Loss : 0.7945310731212231
Epoch : 31 , Loss : 0.7884395526540534
Epoch : 32 , Loss : 0.7826660109868184
Epoch : 33 , Loss : 0.7771881542036208
Epoch : 34 , Loss : 0.7719875676422209
Epoch : 35 , Loss : 0.7670483950327559
Epoch : 36 , Loss : 0.7623565518522912
Epoch : 37 , Loss : 0.7578992477849992
Epoch : 38 , Loss : 0.7536646889577913
Epoch : 39 , Loss : 0.7496418857111469
Epoch : 40 , Loss : 0.745820523244231
Epoch : 41 , Loss : 0.7421908705310027
Epoch : 42 , Loss : 0.7387437132155992
Epoch : 43 , Loss : 0.7354703020849166
Epoch : 44 , Loss : 0.7323623120886618
Epoch : 45 , Loss : 0.7294118088189724
Epoch : 46 , Loss : 0.726611220490825
Epoch : 47 , Loss : 0.723953314130852
Epoch : 48 , Loss : 0.7214311750839136
Epoch : 49 , Loss : 0.7190381891957097

In [21]:
model.weights

tensor([[ 0.5786],
        [ 0.5092],
        [ 0.5209],
        [-0.3135],
        [ 0.0012],
        [-0.2930],
        [-0.0023],
        [-0.3438],
        [ 0.2150],
        [ 0.5851],
        [-0.1359],
        [ 0.1250],
        [-0.1734],
        [-0.0816],
        [ 0.0186],
        [ 0.0400],
        [-0.1485],
        [ 0.0973],
        [ 0.1776],
        [-0.1578],
        [-0.2151],
        [-0.3955],
        [ 0.2920],
        [ 0.4283],
        [-0.0228],
        [-0.0430],
        [-0.2818],
        [-0.4020],
        [ 0.3499],
        [ 0.0612]], dtype=torch.float64, requires_grad=True)

In [22]:
model.bias # as we have started with zero how we can see it has beeen changed

tensor([-0.3241], dtype=torch.float64, requires_grad=True)

### Evaluation

In [23]:
# model evaluation 

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred> 0.7).float()  # if the y_pred is above 0.5 set to 1 
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy : {accuracy.item()}')

print(type(y_pred))
# if y_pred>0.5:
#     y_pred=1
# else:
#     y_pred=0

Accuracy : 0.6255770921707153
<class 'torch.Tensor'>