In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.95531915,  0.54595078, -0.99434598, ..., -1.77773088,
        -0.70673741, -0.98902537],
       [-0.33195899,  0.04054123, -0.31307935, ..., -0.24798785,
         1.10458547,  0.41650279],
       [ 0.06793243, -1.35467384,  0.02691567, ..., -0.09094788,
         0.25463256, -1.27297045],
       ...,
       [ 0.65894843,  0.97543024,  0.72860752, ...,  1.71066671,
         3.05915885,  0.6611324 ],
       [-0.77007533, -1.08891858, -0.7611579 , ..., -0.62460444,
         0.06204023,  0.42414747],
       [-1.18466864, -0.96553222, -1.19647068, ..., -1.61603558,
         0.04930685, -0.38564207]], shape=(455, 30))

In [9]:
y_train

550    B
331    B
225    B
179    B
284    B
      ..
100    M
82     M
370    M
478    B
185    B
Name: diagnosis, Length: 455, dtype: str

### Label Encoding

In [ ]:
encoder = LabelEncoder()  # as diagonisis are in the alphabet we encode them in number her 0 and 1 
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0])

Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [30]:
class mySimpleNN():
    def __init__(self,X):

        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64 , requires_grad=True) # this gives us 30 * 1 matrix of weight
        self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias # z = wx + b
        y_pred = torch.sigmoid(z)   # activation functions
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()  # this is formula for binary cross entropy loss function 
        return loss

### Important Parameters

In [29]:
learning_rate = 0.1 
epochs = 25

### Training Pipeline

In [ ]:
# create model 
model = mySimpleNN(X_train_tensor)
#defin loop

for epoch in range(epochs):
    #forward pass 
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)
        

    # loss calculate

    loss = model.loss_function(y_pred,y_train_tensor)
    # print(f"Epoch : {epoch} Loss : {loss.item()}")

    # backward pass
    loss.backward()

    # parameters update  # wnew = wold - lr.( dL / dW)  and new bias  = bold - lr (dL / db) here lr is learning rate and it is called n eta
    with torch.no_grad():    
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad


    # zero gradients as gradient accumulates so clering them

    model.weights.grad.zero_()
    model.bias.grad.zero_()
    

    # print los in each epoch : 
    print(f"Epoch : {epoch} , Loss : {loss.item()}")



# model.weights

Epoch : 0 , Loss : 3.5344336511033516
Epoch : 1 , Loss : 3.397077953505062
Epoch : 2 , Loss : 3.260659502413701
Epoch : 3 , Loss : 3.1214000167892655
Epoch : 4 , Loss : 2.978041031860261
Epoch : 5 , Loss : 2.8309508671912673
Epoch : 6 , Loss : 2.6742944671189344
Epoch : 7 , Loss : 2.507480839842112
Epoch : 8 , Loss : 2.3381686218347073
Epoch : 9 , Loss : 2.1659682832038882
Epoch : 10 , Loss : 1.996561567576964
Epoch : 11 , Loss : 1.8335553676067162
Epoch : 12 , Loss : 1.676986206030744
Epoch : 13 , Loss : 1.5296455903800734
Epoch : 14 , Loss : 1.3969447426970367
Epoch : 15 , Loss : 1.278912063721163
Epoch : 16 , Loss : 1.1743176323124265
Epoch : 17 , Loss : 1.085591219368045
Epoch : 18 , Loss : 1.0149476096671362
Epoch : 19 , Loss : 0.9605575212482237
Epoch : 20 , Loss : 0.9198375579671193
Epoch : 21 , Loss : 0.8898761837063491
Epoch : 22 , Loss : 0.867893124934481
Epoch : 23 , Loss : 0.8515519102004439
Epoch : 24 , Loss : 0.8390675039851315

In [32]:
model.weights

tensor([[ 0.2445],
        [-0.1547],
        [ 0.3395],
        [ 0.4775],
        [ 0.1647],
        [-0.5575],
        [ 0.3180],
        [ 0.3382],
        [ 0.1765],
        [ 0.6155],
        [ 0.0905],
        [ 0.2114],
        [-0.3837],
        [ 0.2038],
        [ 0.4810],
        [-0.2521],
        [-0.0906],
        [-0.4489],
        [ 0.3508],
        [ 0.1403],
        [ 0.0290],
        [-0.1479],
        [-0.2145],
        [ 0.4690],
        [-0.3324],
        [-0.3622],
        [-0.1849],
        [-0.3727],
        [ 0.0222],
        [ 0.3929]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias # as we have started with zero how we can see it has beeen changed

tensor([-0.0906], dtype=torch.float64, requires_grad=True)

### Evaluation

In [ ]:
# model evaluation 

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred> 0.5).float()  # if the y_pred is above 0.5 set to 1 
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy : {accuracy.item()}')

print(type(y_pred))
# if y_pred>0.5:
#     y_pred=1
# else:
#     y_pred=0

Accuracy : 0.6052631735801697
<class 'torch.Tensor'>