# Using the builtin forward pass . using the activation and linear layers  

So instead of using the handwritten loss functions, activation function. Now we will learn to use the builtin features of the pytorch

In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.23839554,  0.56290312, -0.23478208, ...,  0.75307943,
         1.28391203,  0.74973988],
       [-0.67257196, -0.05145397, -0.70881512, ..., -0.83676451,
         0.95133664, -0.81211873],
       [-1.27273964, -0.28126903, -1.27603049, ..., -1.33562057,
         0.25712587, -0.27368852],
       ...,
       [-0.45105338, -0.82736421, -0.35660301, ...,  0.95933279,
         1.75532957,  2.4067192 ],
       [-0.52489291, -0.93885865, -0.55151651, ..., -0.86523978,
        -0.38219381, -0.22319234],
       [ 0.31983129,  0.11237459,  0.40125143, ...,  1.53499513,
        -0.10289506, -0.06289633]], shape=(455, 30))

In [9]:
y_train

44     M
310    B
467    B
62     M
144    B
      ..
540    B
232    B
5      M
324    B
94     M
Name: diagnosis, Length: 455, dtype: str

### Label Encoding

In [10]:
encoder = LabelEncoder()  # as diagonisis are in the alphabet we encode them in number her 0 and 1 
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1])

Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32)) # this is neccessary as builtin function will use the float instead of the double type tensors
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [15]:
# now using the nn module 
class mySimpleNN(nn.Module):

    def __init__(self,num_features):

        super().__init__()
        self.linear  = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):

        out = self.linear(features)
        out = self.sigmoid(out)
        return out

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()  # this is formula for binary cross entropy loss function 
        return loss

### Important Parameters

In [16]:
learning_rate = 0.1 
epochs = 25

### Training Pipeline

In [17]:
# create model 
model = mySimpleNN(X_train_tensor.shape[1])

#define loop

for epoch in range(epochs):
    #forward pass 
    y_pred = model(X_train_tensor)
    # print(y_pred)
        

    # loss calculate

    loss = model.loss_function(y_pred,y_train_tensor)
    # print(f"Epoch : {epoch} Loss : {loss.item()}")

    # backward pass
    loss.backward()

    # parameters update  # wnew = wold - lr.( dL / dW)  and new bias  = bold - lr (dL / db) here lr is learning rate and it is called n eta
    with torch.no_grad():    
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad


    # zero gradients as gradient accumulates so clering them

    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    

    # print los in each epoch : 
    print(f"Epoch : {epoch} , Loss : {loss.item()}")



# model.weights

Epoch : 0 , Loss : 0.7154926061630249
Epoch : 1 , Loss : 0.7052448987960815
Epoch : 2 , Loss : 0.6982933282852173
Epoch : 3 , Loss : 0.6932501196861267
Epoch : 4 , Loss : 0.6893321871757507
Epoch : 5 , Loss : 0.6861128807067871
Epoch : 6 , Loss : 0.6833592057228088
Epoch : 7 , Loss : 0.6809406876564026
Epoch : 8 , Loss : 0.678779661655426
Epoch : 9 , Loss : 0.6768271327018738
Epoch : 10 , Loss : 0.6750490069389343
Epoch : 11 , Loss : 0.6734205484390259
Epoch : 12 , Loss : 0.6719226837158203
Epoch : 13 , Loss : 0.6705403923988342
Epoch : 14 , Loss : 0.6692607998847961
Epoch : 15 , Loss : 0.6680735945701599
Epoch : 16 , Loss : 0.6669697761535645
Epoch : 17 , Loss : 0.6659417152404785
Epoch : 18 , Loss : 0.6649826169013977
Epoch : 19 , Loss : 0.6640867590904236
Epoch : 20 , Loss : 0.6632488369941711
Epoch : 21 , Loss : 0.6624643802642822
Epoch : 22 , Loss : 0.661729097366333
Epoch : 23 , Loss : 0.661039412021637
Epoch : 24 , Loss : 0.6603918671607971

In [18]:
model.linear.weight

Parameter containing:
tensor([[-0.0026, -0.0160, -0.1319,  0.0222,  0.0689, -0.0534, -0.0636,  0.1022,
         -0.0823, -0.0211, -0.1301,  0.0451, -0.0113,  0.0347, -0.0087,  0.0941,
          0.0547, -0.0086, -0.0213, -0.0188,  0.1079,  0.0795, -0.1327,  0.0516,
         -0.0647, -0.0634,  0.1092,  0.0758,  0.0214, -0.0484]],
       requires_grad=True)

In [19]:
model.linear.bias # as we have started with zero how we can see it has beeen changed

Parameter containing:
tensor([-0.3447], requires_grad=True)

### Evaluation

In [20]:
# model evaluation 

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred> 0.7).float()  # if the y_pred is above 0.5 set to 1 
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy : {accuracy.item()}')

print(type(y_pred))
# if y_pred>0.5:
#     y_pred=1
# else:
#     y_pred=0

Accuracy : 0.5438596606254578
<class 'torch.Tensor'>