In [14]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [20]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
X_train

array([[ 0.42079472,  0.00893362,  0.33465147, ..., -0.42475925,
        -0.33756752, -0.83577442],
       [-0.89429584, -0.49511951, -0.83163362, ...,  0.63355257,
        -0.5636864 ,  0.62441649],
       [ 1.4354551 , -0.78645298,  1.41966378, ...,  0.97005389,
        -0.71706774, -1.1480165 ],
       ...,
       [ 0.26207689, -0.06274366,  0.22161217, ..., -0.02580813,
        -0.97164913, -0.76824802],
       [-0.67322458,  0.19390724, -0.65134831, ..., -0.5246486 ,
         0.42933916, -0.21020984],
       [ 0.37828101, -1.72288196,  0.43778952, ...,  1.04584248,
         0.5052392 ,  0.93125646]], shape=(455, 30))

In [22]:
y_train

263    M
440    B
161    M
366    M
63     B
      ..
460    M
118    M
514    M
160    B
172    M
Name: diagnosis, Length: 455, dtype: str

### Label Encoding

In [23]:
encoder = LabelEncoder()  # as diagonisis are in the alphabet we encode them in number her 0 and 1 
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [24]:
y_train

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1])

Numpy arrays to PyTorch tensors

In [30]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32)) # this is neccessary as builtin function will use the float instead of the double type tensors
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [31]:
X_train_tensor.shape

torch.Size([455, 30])

In [32]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [33]:
# now using the nn module 
class mySimpleNN(nn.Module):

    def __init__(self,num_features):

        super().__init__()
        self.linear  = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):

        out = self.linear(features)
        out = self.sigmoid(out)
        return out

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()  # this is formula for binary cross entropy loss function 
        return loss

### Important Parameters

In [17]:
learning_rate = 0.1 
epochs = 25

### Training Pipeline

In [34]:
# create model 
model = mySimpleNN(X_train_tensor.shape[1])

#define loop

for epoch in range(epochs):
    #forward pass 
    y_pred = model(X_train_tensor)
    # print(y_pred)
        

    # loss calculate

    loss = model.loss_function(y_pred,y_train_tensor)
    # print(f"Epoch : {epoch} Loss : {loss.item()}")

    # backward pass
    loss.backward()

    # parameters update  # wnew = wold - lr.( dL / dW)  and new bias  = bold - lr (dL / db) here lr is learning rate and it is called n eta
    with torch.no_grad():    
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad


    # zero gradients as gradient accumulates so clering them

    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    

    # print los in each epoch : 
    print(f"Epoch : {epoch} , Loss : {loss.item()}")



# model.weights

Epoch : 0 , Loss : 0.8397612571716309
Epoch : 1 , Loss : 0.7808094024658203
Epoch : 2 , Loss : 0.7417454123497009
Epoch : 3 , Loss : 0.7176924347877502
Epoch : 4 , Loss : 0.7036445140838623
Epoch : 5 , Loss : 0.695573091506958
Epoch : 6 , Loss : 0.6907918453216553
Epoch : 7 , Loss : 0.6877418756484985
Epoch : 8 , Loss : 0.6855956315994263
Epoch : 9 , Loss : 0.6839341521263123
Epoch : 10 , Loss : 0.6825496554374695
Epoch : 11 , Loss : 0.6813380122184753
Epoch : 12 , Loss : 0.680245578289032
Epoch : 13 , Loss : 0.6792439818382263
Epoch : 14 , Loss : 0.6783159375190735
Epoch : 15 , Loss : 0.677450954914093
Epoch : 16 , Loss : 0.6766414046287537
Epoch : 17 , Loss : 0.6758817434310913
Epoch : 18 , Loss : 0.6751675009727478
Epoch : 19 , Loss : 0.6744946241378784
Epoch : 20 , Loss : 0.6738598942756653
Epoch : 21 , Loss : 0.6732603311538696
Epoch : 22 , Loss : 0.6726937294006348
Epoch : 23 , Loss : 0.672157347202301
Epoch : 24 , Loss : 0.6716493368148804

In [35]:
model.linear.weight

Parameter containing:
tensor([[-0.1003, -0.0966,  0.0043,  0.0254, -0.0874, -0.0702, -0.0723,  0.1699,
         -0.0630, -0.0338, -0.0070,  0.0321, -0.0942,  0.1025,  0.1597,  0.0532,
         -0.0736,  0.0191, -0.0851, -0.0459, -0.0723, -0.0064, -0.1098,  0.1831,
         -0.0603,  0.1931, -0.0382,  0.0193,  0.0810,  0.0393]],
       requires_grad=True)

In [36]:
model.linear.bias # as we have started with zero how we can see it has beeen changed

Parameter containing:
tensor([-0.2753], requires_grad=True)

### Evaluation

In [37]:
# model evaluation 

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred> 0.7).float()  # if the y_pred is above 0.5 set to 1 
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy : {accuracy.item()}')

print(type(y_pred))
# if y_pred>0.5:
#     y_pred=1
# else:
#     y_pred=0

Accuracy : 0.6228070259094238
<class 'torch.Tensor'>

# Using the builtin loss function and optimizer

In [ ]:
learning_rate = 0.1 
epochs = 25

In [ ]:
loss_function = nn.BCEloss() # binary cross entropy loss built in in nn module

In [ ]:
class mySimpleNN1(nn.Module):

    def __init__(self,num_features):

        super().__init__()
        self.linear  = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):

        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [ ]:
# create model 
model = mySimpleNN(X_train_tensor.shape[1])

#define loop

for epoch in range(epochs):
    #forward pass 
    y_pred = model(X_train_tensor)
    # print(y_pred)
        

    # loss calculate

    loss = model.loss_function(y_pred,y_train_tensor)
    # print(f"Epoch : {epoch} Loss : {loss.item()}")

    # backward pass
    loss.backward()

    # parameters update  # wnew = wold - lr.( dL / dW)  and new bias  = bold - lr (dL / db) here lr is learning rate and it is called n eta
    with torch.no_grad():    
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad


    # zero gradients as gradient accumulates so clering them

    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    

    # print los in each epoch : 
    print(f"Epoch : {epoch} , Loss : {loss.item()}")



# model.weights